name: build development images

on:
  push:
    branches:
      - dev

env:
  SINGULARITY_VERSION: "3.8.3"

jobs:
  build_docker_dev:
    name: build docker development image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/fraposa_pgsc' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: downcase GITHUB_REPOSITORY
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ghcr.io/${{ env.REPO }}:dev

      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PACKAGE_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          dry-run: false
          keep-last: 3
          prune-untagged: true

  build_singularity_dev:
    needs: build_docker_dev
    name: build singularity development image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/fraposa_pgsc' }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Cache singularity setup
        id: cache-singularity
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64
          key: ${{ runner.os }}-singularity-${{ env.SINGULARITY_VERSION }}

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        with:
          singularity-version: ${{ env.SINGULARITY_VERSION }}

      - name: Add singularity to path
        if: steps.cache-singularity.outputs.cache-hit == 'true'
        run: |
          echo "/opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64/bin" >> $GITHUB_PATH

      - name: downcase GITHUB_REPOSITORY
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: Build singularity image
        run: singularity build img.sif "docker://ghcr.io/${{ env.REPO }}:dev"

      - name: Push singularity image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | singularity remote login -u "$GITHUB_ACTOR" --password-stdin oras://ghcr.io
          singularity push img.sif "oras://ghcr.io/${{ env.REPO }}:dev-singularity"
