name: Publish fraposa-pgsc to PyPI

on:
  release:
    types: [published]    
    
jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
            
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v3

      - name: Build package
        run: poetry build --no-interaction

      - name: Publish package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
